### ISSUE TITLE
[BUG] phoenix fpc fp not working

### ISSUE THREAD

**Issue by San0621** [BlissRoms/bug_reports#34]
When i instantly unlock the device by fp after lock the device then it is working. When i unlock device after 2-3 minutes then fp not working need to press power button for make it working.

**Device:**
 - Codename (phoenix):  
 - Build date (ex. 2020-06-10)
**Logcat**

<< log_count = 274 >>>
[06-12 13:13:28.370 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

[06-12 13:13:31.856 7878:7898 D/OpenGLRenderer]
endAllActiveAnimators on 0x7dece7e100 (MenuPopupWindow$MenuDropDownListView) with handle 0x7e5c20d9e0

[06-12 13:13:36.632 1436:1608 E/LightsService]
Light requested not available on this device. 2

[06-12 13:13:38.269 1436:2131 E/LightsService]
Light requested not available on this device. 2

[06-12 13:13:43.416 1436:1608 E/LightsService]
Light requested not available on this device. 2

[06-12 13:13:43.651 1436:2132 D/WindowManager]
powerPress: eventTime=1065307 interactive=true count=1 beganFromNonInteractive=false mShortPressOnPowerBehavior=1

[06-12 13:13:43.651 1436:2132 I/PowerManagerService]
Going to sleep due to power_button (uid 1000)...

[06-12 13:13:43.652 1436:1436 W/UsageStatsService]
Event reported without a package name, eventType:16

[06-12 13:13:43.657 1436:1608 E/libEGL]
eglCreateWindowSurfaceTmpl:719 error 300b (EGL_BAD_NATIVE_WINDOW)

[06-12 13:13:43.904 1436:1608 I/DisplayPowerController]
Blocking screen off

[06-12 13:13:43.904 1436:1608 I/DisplayPowerController]
Unblocked screen off after 1 ms

[06-12 13:13:43.921 832:907 I/DisplayFeatureHal]
threadFuncBacklight: set brightness to 0

[06-12 13:13:43.926 1436:1608 D/ActivityTaskManager]
Top Process State changed to PROCESS_STATE_TOP_SLEEPING

[06-12 13:13:43.931 1436:2154 E/WifiNative]
Could not get Iface object for interface null

[06-12 13:13:43.932 1436:1601 E/BatteryExternalStatsWorker]
no controller energy info supplied for bluetooth

[06-12 13:13:43.935 799:821 I/sensors-hal]
activate:147, android.sensor.device_orientation/27 en=0

[06-12 13:13:43.936 799:821 I/sensors-hal]
activate:158, android.sensor.device_orientation/27 en=0 completed

[06-12 13:13:43.941 1436:1608 E/libEGL]
eglDestroySurfaceImpl:901 error 300d (EGL_BAD_SURFACE)

[06-12 13:13:43.942 1436:1608 E/ColorFade]
eglDestroySurface failed: error 12301
java.lang.Throwable
	at com.android.server.display.ColorFade.logEglError(ColorFade.java:701)
	at com.android.server.display.ColorFade.destroyEglSurface(ColorFade.java:642)
	at com.android.server.display.ColorFade.dismissResources(ColorFade.java:339)
	at com.android.server.display.DisplayPowerState.dismissColorFadeResources(DisplayPowerState.java:216)
	at com.android.server.display.DisplayPowerController.animateScreenStateChange(DisplayPowerController.java:1528)
	at com.android.server.display.DisplayPowerController.updatePowerState(DisplayPowerController.java:902)
	at com.android.server.display.DisplayPowerController.access$800(DisplayPowerController.java:91)
	at com.android.server.display.DisplayPowerController$DisplayControllerHandler.handleMessage(DisplayPowerController.java:1952)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:44)

[06-12 13:13:43.944 1436:1533 I/DisplayManagerService]
Display device changed state: "Built-in Screen", OFF

[06-12 13:13:43.952 688:688 D/SurfaceFlinger]
Setting power mode 0 on display 19260668995500161

[06-12 13:13:43.954 690:690 I/SDM]
DisplayBase::SetDisplayState: Set state = 0, display 28-0, teardown = 0

[06-12 13:13:43.961 7878:7878 D/LogcatReader]
[Logcat] onActivityInBackground

[06-12 13:13:43.976 798:798 I/android.hardware.power@1.3-service.sm6150-libperfmgr]
getPlatformLowPowerStats not supported. Do nothing.

[06-12 13:13:43.976 798:798 I/android.hardware.power@1.3-service.sm6150-libperfmgr]
getSubsystemLowPowerStats not supported. Do nothing.

[06-12 13:13:43.981 781:781 I/netd]
trafficSwapActiveStatsMap() <0.63ms>

[06-12 13:13:43.983 781:781 I/netd]
tetherGetStats() <1.05ms>

[06-12 13:13:43.987 2218:2675 I/DataUsageUtils]
Subscription is not active: -1

[06-12 13:13:43.996 781:781 I/netd]
trafficSwapActiveStatsMap() <0.21ms>

[06-12 13:13:43.998 781:781 I/netd]
tetherGetStats() <1.32ms>

[06-12 13:13:44.121 690:690 W/SDM]
ResourceImpl::Perform: Invalid command 4

[06-12 13:13:44.122 688:688 D/SurfaceFlinger]
Finished setting power mode 0 on display 19260668995500161

[06-12 13:13:44.123 1436:2196 D/SurfaceControl]
Excessive delay in setPowerMode()

[06-12 13:13:44.124 937:1103 I//vendor/bin/mi_thermald]
generic_set_level: set generic device battery to 0

[06-12 13:13:44.126 1436:1608 I/DreamManagerService]
Entering dreamland.

[06-12 13:13:44.128 1436:1608 I/PowerManagerService]
Dozing...

[06-12 13:13:44.129 1436:1530 I/DreamController]
Starting dream: name=ComponentInfo{com.android.systemui/com.android.systemui.doze.DozeService}, isTest=false, canDoze=true, userId=0

[06-12 13:13:44.146 3299:3299 I/AiAiCaptions]
isCaptionsSecureSettingsEnabled() can't find setting.

[06-12 13:13:44.155 2218:2218 D/StatusBar]
updateQsExpansionEnabled - QS Expand enabled: false

[06-12 13:13:44.212 2218:2218 I/chatty]
uid=10182(com.android.systemui) identical 1 line

[06-12 13:13:44.225 2218:2218 D/StatusBar]
updateQsExpansionEnabled - QS Expand enabled: false

[06-12 13:13:44.237 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

[06-12 13:13:44.248 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

[06-12 13:13:44.261 3258:3258 D/com.motorola.faceunlock.service.FaceAuthService]
OnReceive intent = Intent { act=android.intent.action.SCREEN_OFF flg=0x50200010 }

[06-12 13:13:44.269 1436:2154 E/WifiClientModeImpl]
getWifiLinkLayerStats called without an interface

[06-12 13:13:44.271 786:843 D/audio_hw_primary]
adev_set_parameters: enter: screen_state=off

[06-12 13:13:44.271 786:843 D/audio_hw_hfp]
hfp_set_parameters: enter

[06-12 13:13:44.271 786:843 W/sound_trigger_hw]
sound_trigger_hw_call_back: Unknown event 15

[06-12 13:13:44.271 786:843 D/audio_hw_hfp]
hfp_set_parameters: enter

[06-12 13:13:44.271 786:843 D/audio_hw_extn]
audio_extn_fm_set_parameters: Enter

[06-12 13:13:44.271 786:843 D/audio_hw_hfp]
hfp_set_parameters: enter

[06-12 13:13:44.271 786:843 V/ultrasound_extn]
ultrasound_extn_set_parameters: enter

[06-12 13:13:44.271 786:843 V/ultrasound_extn]
ultrasound_handle_screen_on_message: enter

[06-12 13:13:44.271 786:843 V/ultrasound_extn]
ultrasound_handle_screen_on_message: exit

[06-12 13:13:44.271 786:843 V/ultrasound_extn]
ultrasound_handle_sensor_fusion_message: enter

[06-12 13:13:44.271 786:843 V/ultrasound_extn]
ultrasound_handle_sensor_fusion_message: exit

[06-12 13:13:44.271 786:843 V/ultrasound_extn]
ultrasound_extn_set_parameters: usecase handling parms:screen_state=off

[06-12 13:13:44.277 1436:1436 W/AlarmManager]
Unrecognized alarm listener com.android.server.-$$Lambda$DeviceIdleController$pUAsoxLVwpJ9Ac-b6Wbul1k9bIw@22d4493

[06-12 13:13:44.279 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

[06-12 13:13:44.322 1436:1533 W/UsageStatsService]
Event reported without a package name, eventType:17

[06-12 13:13:44.324 2218:2218 D/StatusBar]
updateQsExpansionEnabled - QS Expand enabled: false

[06-12 13:13:44.327 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

[06-12 13:13:44.328 2218:2218 I/chatty]
uid=10182(com.android.systemui) identical 2 lines

[06-12 13:13:44.328 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

[06-12 13:13:44.378 2218:2218 D/KeyguardUpdateMonitor]
onKeyguardVisibilityChanged(true)

[06-12 13:13:44.391 1228:1228 D/fpc_fingerprint_hal]
fpc_get_authenticator_id

[06-12 13:13:44.391 2218:2218 D/KeyguardUpdateMonitor]
fingerprintRunningState: 1

[06-12 13:13:44.392 1436:1436 V/FingerprintService]
startAuthentication(com.android.systemui)

[06-12 13:13:44.392 1436:1436 V/FingerprintService]
starting client AuthenticationClientImpl(com.android.systemui) targetUserId: 0 currentUserId: 0 cookie: 0/0

[06-12 13:13:44.392 1228:1228 D/fpc_fingerprint_hal]
fpc_authenticate operation_id 0

[06-12 13:13:44.392 1228:1228 D/fpc_tac]
fpc_tee_set_cancel

[06-12 13:13:44.392 1228:1228 D/fpc_fingerprint_hal]
--> set_cancel_image_injection

[06-12 13:13:44.392 1228:1228 D/fpc_fingerprint_hal]
fpc_worker_join_task

[06-12 13:13:44.392 1228:1228 D/fpc_tac]
fpc_tee_clear_cancel

[06-12 13:13:44.393 1228:1228 D/fpc_fingerprint_hal]
--> clear_cancel_image_injection

[06-12 13:13:44.393 1228:1228 D/fpc_fingerprint_hal]
<-- clear_cancel_image_injection

[06-12 13:13:44.393 1228:1228 D/fpc_fingerprint_hal]
fpc_navigation_pause

[06-12 13:13:44.393 1228:1228 D/fpc_fingerprint_hal]
fpc_worker_join_task

[06-12 13:13:44.393 1228:1516 D/fpc_tac]
fpc_irq_wait: poll status: 1, revents [0]: 0, [1]: 1

[06-12 13:13:44.393 1228:1516 E/fpc_tac]
fpc_irq_wait {{23,10,0},{21,1,1}}

[06-12 13:13:44.393 1228:1516 E/fpc_tac]
fpc_irq_wait error -7

[06-12 13:13:44.395 2218:2218 D/StatusBar]
disable<e i a s b H!R!c s > disable2<q i n >

[06-12 13:13:44.397 2218:2218 D/StatusBar]
disable<e i a s b H R c s > disable2<q i n >

[06-12 13:13:44.397 2218:2218 I/chatty]
uid=10182(com.android.systemui) identical 1 line

[06-12 13:13:44.397 2218:2218 D/StatusBar]
disable<e i a s b H R c s > disable2<q i n >

[06-12 13:13:44.413 1228:1228 D/fpc_fingerprint_hal]
fpc_worker_join_task

[06-12 13:13:44.414 1228:1228 D/fpc_fingerprint_hal]
fpc_navigation_pause

[06-12 13:13:44.414 1228:1228 D/fpc_fingerprint_hal]
fpc_worker_run_task

[06-12 13:13:44.414 1228:1486 D/fpc_fingerprint_hal]
do_authenticate

[06-12 13:13:44.414 1228:1486 D/fpc_tac]
fpc_tee_set_auth_challenge

[06-12 13:13:44.415 1228:1486 D/fpc_tac]
get_kpi_status: property value='0' kpi_active=0

[06-12 13:13:44.416 1228:1486 D/fpc_fingerprint_hal]
--> is_img_inj_enabled

[06-12 13:13:44.416 1228:1486 D/fpc_fingerprint_hal]
<-- is_img_inj_enabled

[06-12 13:13:44.416 1228:1486 D/fpc_tac]
--> fpc_tee_capture_image

[06-12 13:13:44.416 1228:1486 D/fpc_tac]
--> fpc_tee_capture_image_internal

[06-12 13:13:44.416 1228:1486 D/fpc_tac]
--> fpc_tee_wait_finger_lost

[06-12 13:13:44.417 1436:1436 W/FingerprintService]
client com.android.systemui is authenticating...

[06-12 13:13:44.457 3397:3397 D/NfcService]
MSG_APPLY_SCREEN_STATE 2

[06-12 13:13:44.469 1228:1486 D/fpc_tac]
<-- fpc_tee_wait_finger_lost, return: 0

[06-12 13:13:44.478 9258:9258 I/DeviceStatusMonitor]
onReceive() : Action = android.intent.action.SCREEN_OFF

[06-12 13:14:11.242 1228:1486 D/fpc_tac]
fpc_irq_wait: poll status: 1, revents [0]: 10, [1]: 0

[06-12 13:14:11.242 1228:1486 D/fpc_fingerprint_hal]
send_finger_notify: send finger DOWN notify

[06-12 13:14:11.242 1228:1486 W/android.hardware.biometrics.fingerprint@2.1-service]
onAcquired(6) (22)

[06-12 13:14:11.242 1228:1486 D/fpc_tac]
Waited more than 500 ms, reset qualification counter

[06-12 13:14:11.243 548:548 I/hwservicemanager]
getTransport: Cannot find entry vendor.qti.hardware.perf@2.0::IPerf/default in either framework or device manifest.

[06-12 13:14:11.243 1436:1436 V/FingerprintService]
Acquired: 6 22

[06-12 13:14:11.244 2218:2218 W/FingerprintManager]
Invalid acquired message: 6, 22

[06-12 13:14:11.245 1228:1486 E/ANDR-PERF]
IPerf:: Perf HAL Service is not available.

[06-12 13:14:11.245 1228:1486 E/fpc_tac]
fpc_perf_lock_acquire: Failed to acquire perf lock, err: -1

[06-12 13:14:11.269 1436:1460 I/BatteryStatsService]
In wakeup_callback: resumed from suspend

[06-12 13:14:11.274 1436:2132 I/PowerManagerService]
Waking up from Dozing (uid=1000, reason=WAKE_REASON_POWER_BUTTON, details=android.policy:POWER)...

[06-12 13:14:11.274 1436:1436 W/UsageStatsService]
Event reported without a package name, eventType:15

[06-12 13:14:11.278 1436:2132 E/LightsService]
Light requested not available on this device. 2

[06-12 13:14:11.285 1436:1608 I/DisplayPowerController]
Blocking screen on until initial contents have been drawn.

[06-12 13:14:11.288 1436:1533 I/DisplayManagerService]
Display device changed state: "Built-in Screen", ON

[06-12 13:14:11.288 688:688 D/SurfaceFlinger]
Setting power mode 2 on display 19260668995500161

[06-12 13:14:11.288 690:690 I/SDM]
DisplayBase::SetDisplayState: Set state = 1, display 28-0, teardown = 0

[06-12 13:14:11.323 2218:2218 D/StatusBar]
disable<e i a s b H R c s > disable2<q i n >

[06-12 13:14:11.324 2218:2218 D/StatusBar]
disable<e i a s b H R c s > disable2<q i n >

[06-12 13:14:11.324 2218:2218 D/StatusBar]
updateQsExpansionEnabled - QS Expand enabled: true

[06-12 13:14:11.327 1228:1486 D/fpc_tac]
<-- fpc_tee_capture_image_internal, return: 3

[06-12 13:14:11.327 1228:1486 D/fpc_tac]
<-- fpc_tee_capture_image, return: 3

[06-12 13:14:11.327 1228:1486 D/fpc_fingerprint_hal]
do_authenticate capture_status: 3, identify_status: 0, id: 0

[06-12 13:14:11.327 1228:1486 D/fpc_fingerprint_hal]
send_notification FPC_STATUS_FINGER_LOST

[06-12 13:14:11.327 1228:1486 W/android.hardware.biometrics.fingerprint@2.1-service]
onAcquired(5) (0)

[06-12 13:14:11.327 1228:1486 D/fpc_tac]
get_kpi_status: property value='0' kpi_active=0

[06-12 13:14:11.327 1228:1486 D/fpc_fingerprint_hal]
--> is_img_inj_enabled

[06-12 13:14:11.327 1228:1486 D/fpc_fingerprint_hal]
<-- is_img_inj_enabled

[06-12 13:14:11.327 1228:1486 D/fpc_tac]
--> fpc_tee_capture_image

[06-12 13:14:11.327 1228:1486 D/fpc_tac]
--> fpc_tee_capture_image_internal

[06-12 13:14:11.327 1228:1486 D/fpc_tac]
--> fpc_tee_wait_finger_lost

[06-12 13:14:11.333 1436:1436 V/FingerprintService]
Acquired: 5 0

[06-12 13:14:11.336 1436:2154 E/WifiClientModeImpl]
getWifiLinkLayerStats called without an interface

[06-12 13:14:11.337 786:843 D/audio_hw_primary]
adev_set_parameters: enter: screen_state=on

[06-12 13:14:11.337 786:843 D/audio_hw_hfp]
hfp_set_parameters: enter

[06-12 13:14:11.337 786:843 W/sound_trigger_hw]
sound_trigger_hw_call_back: Unknown event 15

[06-12 13:14:11.337 786:843 D/audio_hw_hfp]
hfp_set_parameters: enter

[06-12 13:14:11.337 786:843 D/audio_hw_extn]
audio_extn_fm_set_parameters: Enter

[06-12 13:14:11.337 786:843 D/audio_hw_hfp]
hfp_set_parameters: enter

[06-12 13:14:11.337 786:843 V/ultrasound_extn]
ultrasound_extn_set_parameters: enter

[06-12 13:14:11.337 786:843 V/ultrasound_extn]
ultrasound_handle_screen_on_message: enter

[06-12 13:14:11.337 786:843 V/ultrasound_extn]
ultrasound_handle_screen_on_message: exit

[06-12 13:14:11.337 786:843 V/ultrasound_extn]
ultrasound_handle_sensor_fusion_message: enter

[06-12 13:14:11.337 786:843 V/ultrasound_extn]
ultrasound_handle_sensor_fusion_message: exit

[06-12 13:14:11.337 786:843 V/ultrasound_extn]
ultrasound_extn_set_parameters: usecase handling parms:screen_state=on

[06-12 13:14:11.339 1436:2132 I/WindowManager]
Suppressed redundant power key press while already in the process of turning the screen on.

[06-12 13:14:11.342 1228:1486 D/fpc_tac]
fpc_irq_wait: poll status: 1, revents [0]: 10, [1]: 0

[06-12 13:14:11.357 1228:1486 D/fpc_tac]
<-- fpc_tee_wait_finger_lost, return: 0

[06-12 13:14:11.361 2376:2829 W/IWlanNetworkService]
52 > Response Processed

[06-12 13:14:11.364 937:1103 I//vendor/bin/mi_thermald]
generic_set_level: set generic device battery to 9

[06-12 13:14:11.373 690:690 W/SDM]
ResourceImpl::Perform: Invalid command 4

[06-12 13:14:11.373 2218:2218 D/StatusBar]
updateQsExpansionEnabled - QS Expand enabled: true

[06-12 13:14:11.373 688:688 D/SurfaceFlinger]
Finished setting power mode 2 on display 19260668995500161

[06-12 13:14:11.384 2376:2829 W/IWlanNetworkService]
53 > Response Processed

[06-12 13:14:11.400 799:799 I/sensors-hal]
batch:180, android.sensor.device_orientation/27, period=66667000, max_latency=0

[06-12 13:14:11.400 799:799 I/sensors-hal]
batch:189, android.sensor.device_orientation/27, period=66667000, max_latency=0 request completed

[06-12 13:14:11.400 799:799 I/sensors-hal]
activate:147, android.sensor.device_orientation/27 en=1

[06-12 13:14:11.401 799:799 I/sensors-hal]
get_qmi_debug_flag:230, support_qmi_debug : false

[06-12 13:14:11.401 1436:2154 E/WifiNative]
Could not get Iface object for interface null

[06-12 13:14:11.403 1436:1601 E/BatteryExternalStatsWorker]
no controller energy info supplied for bluetooth

[06-12 13:14:11.406 799:799 I/sensors-hal]
activate:158, android.sensor.device_orientation/27 en=1 completed

[06-12 13:14:11.406 1436:1608 I/DisplayPowerController]
Unblocked screen on after 121 ms

[06-12 13:14:11.407 1436:1608 W/PowerManagerService]
Screen on took 207 ms

[06-12 13:14:11.407 1436:1608 I/DreamManagerService]
Gently waking up from dream.

[06-12 13:14:11.407 1436:1530 I/DreamManagerService]
Performing gentle wake from dream.

[06-12 13:14:11.420 832:907 I/DisplayFeatureHal]
threadFuncBacklight: set brightness to 112

[06-12 13:14:11.428 798:798 I/android.hardware.power@1.3-service.sm6150-libperfmgr]
getPlatformLowPowerStats not supported. Do nothing.

[06-12 13:14:11.428 798:798 I/android.hardware.power@1.3-service.sm6150-libperfmgr]
getSubsystemLowPowerStats not supported. Do nothing.

[06-12 13:14:11.429 2376:2829 W/IWlanNetworkService]
54 > Response Processed

[06-12 13:14:11.430 781:781 I/netd]
trafficSwapActiveStatsMap() <0.36ms>

[06-12 13:14:11.431 1436:2228 I/DreamManagerService]
Leaving dreamland.

[06-12 13:14:11.431 1436:1530 I/DreamManagerService]
Performing gentle wake from dream.

[06-12 13:14:11.431 1436:1530 I/DreamController]
Stopping dream: name=ComponentInfo{com.android.systemui/com.android.systemui.doze.DozeService}, isTest=false, canDoze=true, userId=0

[06-12 13:14:11.432 781:781 I/netd]
tetherGetStats() <0.96ms>

[06-12 13:14:11.432 1436:1436 W/AlarmManager]
Unrecognized alarm listener com.android.server.job.controllers.idle.-$$Lambda$DeviceIdlenessTracker$-H1-ZwZAJ-vh10A0PeYXaZLj_R0@d686e22

[06-12 13:14:11.438 3397:3397 D/NfcService]
MSG_APPLY_SCREEN_STATE 4

[06-12 13:14:11.443 4065:4065 I/WeatherService]
screenStateListener trigger update after update error

[06-12 13:14:11.466 9258:9258 I/DeviceStatusMonitor]
onReceive() : Action = android.intent.action.SCREEN_ON

[06-12 13:14:11.469 2218:2218 D/ImageWallpaper]
wallpaper visibility changes to: true

[06-12 13:14:11.479 4065:5612 W/WeatherService]
locations disabled

[06-12 13:14:11.479 4065:5612 W/WeatherService]
no location

[06-12 13:14:12.095 799:10940 I/sensors-hal]
handle_indication_realtime:406,  SCHED_FIFO(10) for qmi_cbk

[06-12 13:14:12.170 2218:2218 D/StatusBar]
disable<e i a s b H R c s > disable2<q i n >

[06-12 13:14:13.309 1436:3362 D/LockSettingsService]
spBasedDoVerifyCredential: user=0 challengeType=0 hasEnrolledBiometrics=true

[06-12 13:14:12.170 2218:2218 I/chatty]
uid=10182(com.android.systemui) identical 1 line

[06-12 13:14:12.192 2218:2218 D/StatusBar]
disable<e i a s b H R c s > disable2<q i n >

[06-12 13:14:13.310 3258:3275 D/com.motorola.faceunlock.service.FaceAuthService]
generateChallenge + 600

[06-12 13:14:13.380 949:949 D/keystore]
AddAuthenticationToken: timestamp = 1586884, time_received = 1088

[06-12 13:14:13.413 949:949 D/keystore]
AddAuthenticationToken: timestamp = 1586918, time_received = 1088

[06-12 13:14:13.429 949:949 D/keystore]
AddAuthenticationToken: timestamp = 1586934, time_received = 1088

[06-12 13:14:13.431 949:949 I/keystore]
calling unlock when already unlocked, ignoring.

[06-12 13:14:13.432 1436:3362 I/LockSettingsService]
Unlocking user 0 with secret only, length 32

[06-12 13:14:13.432 1436:3362 I/ActivityManager]
unlocking user 0

[06-12 13:14:13.432 1436:3362 D/LockSettingsService]
unlockUser finished

[06-12 13:14:13.432 1436:3362 D/ActivityManager]
UserController event: finishUserUnlocking(0)

[06-12 13:14:13.433 1436:3362 I/LockSettingsService]
Disabling escrow token on user 0

[06-12 13:14:13.434 1436:3362 I/LockSettingsService]
Caching SP for user 0

[06-12 13:14:13.434 1436:1436 D/FingerprintService]
setActiveUser(0)

[06-12 13:14:13.432 1436:3362 D/LockSettingsService]
unlockUser finished

[06-12 13:14:13.434 1228:1228 D/fpc_fingerprint_hal]
fpc_get_authenticator_id

[06-12 13:14:13.436 1436:1436 D/FaceService]
setActiveUser(0)

[06-12 13:14:13.439 1436:1436 W/FaceService]
Ignoring lockout reset, no templates enrolled

[06-12 13:14:13.439 3258:3275 D/com.motorola.faceunlock.service.FaceAuthService]
revokeChallenge

[06-12 13:14:13.439 2218:2218 D/StatusBar]
updateQsExpansionEnabled - QS Expand enabled: true

[06-12 13:14:13.440 1436:1436 I/LockSettingsService]
Removing SP from cache for user 0

[06-12 13:14:13.446 1436:7045 D/KeySyncTask]
Key sync not needed.

[06-12 13:14:13.583 1436:1436 V/FingerprintService]
Stopping client com.android.systemui, fromClient: true

[06-12 13:14:13.583 2218:2218 D/KeyguardUpdateMonitor]
fingerprintRunningState: 2

[06-12 13:14:13.583 1228:1228 D/fpc_fingerprint_hal]
fpc_cancel

[06-12 13:14:13.583 1228:1228 D/fpc_tac]
fpc_tee_set_cancel

[06-12 13:14:13.583 1228:1228 D/fpc_fingerprint_hal]
--> set_cancel_image_injection

[06-12 13:14:13.584 1228:1228 D/fpc_fingerprint_hal]
fpc_worker_join_task

[06-12 13:14:13.584 1228:1486 D/fpc_tac]
fpc_irq_wait: poll status: 1, revents [0]: 0, [1]: 1

[06-12 13:14:13.584 1228:1486 E/fpc_tac]
fpc_irq_wait {{23,10,0},{14,1,1}}

[06-12 13:14:13.584 1228:1486 E/fpc_tac]
fpc_irq_wait error -7

[06-12 13:14:13.584 1228:1486 E/fpc_tac]
fpc_tee_wait_finger_down,  error status: -7

[06-12 13:14:13.584 1228:1486 D/fpc_tac]
Waited more than 500 ms, reset qualification counter

[06-12 13:14:13.584 1436:3386 D/ActivityTaskManager]
Top Process State changed to PROCESS_STATE_TOP

[06-12 13:14:13.598 1228:1486 D/fpc_tac]
<-- fpc_tee_capture_image_internal, return: -7

[06-12 13:14:13.598 1228:1486 D/fpc_tac]
<-- fpc_tee_capture_image, return: -7

[06-12 13:14:13.606 1228:1486 E/fpc_fingerprint_hal]
do_authenticate failed FPC_ERROR_CANCELLED

[06-12 13:14:13.606 1228:1486 D/fpc_fingerprint_hal]
do_authenticate: wait for finger lost

[06-12 13:14:13.606 1228:1486 D/fpc_tac]
--> fpc_tee_wait_finger_lost

[06-12 13:14:13.608 2218:2218 D/StatusBar]
updateQsExpansionEnabled - QS Expand enabled: true

[06-12 13:14:13.608 2218:2218 D/StatusBar]
disable<e i a s b H R c s > disable2<q i n >

[06-12 13:14:13.612 2218:2218 D/StatusBar]
updateQsExpansionEnabled - QS Expand enabled: true

[06-12 13:14:13.618 1228:1486 D/fpc_tac]
fpc_irq_wait: poll status: 1, revents [0]: 0, [1]: 1

[06-12 13:14:13.618 1228:1486 E/fpc_tac]
fpc_irq_wait {{23,10,0},{14,1,1}}

[06-12 13:14:13.618 1228:1486 E/fpc_tac]
fpc_irq_wait error -7

[06-12 13:14:13.618 1228:1486 D/fpc_tac]
<-- fpc_tee_wait_finger_lost, return: -7

[06-12 13:14:13.618 1228:1486 D/fpc_fingerprint_hal]
fpc_navigation_resume

[06-12 13:14:13.618 1228:1486 D/fpc_fingerprint_hal]
fpc_worker_run_task

[06-12 13:14:13.618 1228:1516 D/fpc_fingerprint_hal]
nav_loop

[06-12 13:14:13.618 1228:1228 D/fpc_tac]
fpc_tee_clear_cancel

[06-12 13:14:13.618 1228:1228 D/fpc_fingerprint_hal]
--> clear_cancel_image_injection

[06-12 13:14:13.618 1228:1228 D/fpc_fingerprint_hal]
<-- clear_cancel_image_injection

[06-12 13:14:13.618 1228:1228 D/fpc_fingerprint_hal]
fpc_navigation_pause

[06-12 13:14:13.618 1228:1228 D/fpc_fingerprint_hal]
fpc_worker_join_task

[06-12 13:14:13.618 2218:2218 D/StatusBar]
disable<e i a s b h!r!c s > disable2<q i n >

[06-12 13:14:13.618 7878:7878 D/LogcatReader]
[Logcat] onActivityInForeground

[06-12 13:14:13.618 7878:7878 D/LogcatReader]
[Logcat] Posting pending logs

[06-12 13:14:13.626 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

[06-12 13:14:13.627 2218:2218 D/KeyguardUpdateMonitor]
onKeyguardVisibilityChanged(false)

[06-12 13:14:13.632 1228:1516 D/fpc_tac]
fpc_irq_wait: poll status: 1, revents [0]: 0, [1]: 1

[06-12 13:14:13.632 1228:1516 E/fpc_tac]
fpc_irq_wait {{23,10,0},{21,1,1}}

[06-12 13:14:13.632 1228:1516 E/fpc_tac]
fpc_irq_wait error -7

[06-12 13:14:13.632 1228:1516 E/fpc_fingerprint_hal]
nav_loop, status = -7

[06-12 13:14:13.632 1228:1228 D/fpc_fingerprint_hal]
fpc_worker_join_task

[06-12 13:14:13.632 1228:1228 D/fpc_fingerprint_hal]
fpc_navigation_resume

[06-12 13:14:13.632 1228:1228 D/fpc_fingerprint_hal]
fpc_worker_run_task

[06-12 13:14:13.632 1228:1516 D/fpc_fingerprint_hal]
nav_loop

[06-12 13:14:13.632 1228:1228 W/android.hardware.biometrics.fingerprint@2.1-service]
onError(5)

[06-12 13:14:13.633 1436:1436 W/FingerprintService]
client com.android.systemui is no longer authenticating

[06-12 13:14:13.634 1436:1436 V/FingerprintService]
handleError(client=com.android.systemui, error = 5)

[06-12 13:14:13.634 1436:1436 V/BiometricStats]
Error latency: -1

[06-12 13:14:13.634 1436:1436 V/FingerprintService]
Done with client: com.android.systemui

[06-12 13:14:13.635 1436:1533 W/UsageStatsService]
Event reported without a package name, eventType:18

[06-12 13:14:13.636 1436:1533 W/AlarmManager]
Unrecognized alarm listener com.android.server.-$$Lambda$DeviceIdleController$pUAsoxLVwpJ9Ac-b6Wbul1k9bIw@22d4493

[06-12 13:14:13.640 1436:1595 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.USER_PRESENT flg=0x24200010 } to com.google.android.gms/.auth.setup.devicesignals.LockScreenReceiver

[06-12 13:14:13.640 1436:1595 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.USER_PRESENT flg=0x24200010 } to com.google.android.gms/.trustagent.UserPresentBroadcastReceiver

[06-12 13:14:13.640 3258:3258 D/com.motorola.faceunlock.service.FaceAuthService]
OnReceive intent = Intent { act=android.intent.action.USER_PRESENT flg=0x24200010 }

[06-12 13:14:13.640 1436:1595 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.USER_PRESENT flg=0x24200010 } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver

[06-12 13:14:13.642 3358:3358 I/GsaVoiceInteractionSrv]
O received Intent { act=android.intent.action.USER_PRESENT flg=0x24200010 }

[06-12 13:14:13.645 3397:3397 D/NfcService]
MSG_APPLY_SCREEN_STATE 8

[06-12 13:14:13.650 7878:7878 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected

[06-12 13:14:13.655 8986:8986 I/TrustAgent]
TAG: TrustAgent. [OnbodyLure] User present, Check whether to show notification [CONTEXT service_id=84 ]

[06-12 13:14:13.668 2218:2218 D/KeyguardUpdateMonitor]
fingerprintRunningState: 0

[06-12 13:14:13.671 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

[06-12 13:14:13.683 2218:2675 I/DataUsageUtils]
Subscription is not active: -1

[06-12 13:14:13.683 1228:1516 D/fpc_fingerprint_hal]
nav_loop waiting for finger down

[06-12 13:14:13.689 781:781 I/netd]
trafficSwapActiveStatsMap() <0.27ms>

[06-12 13:14:13.691 781:781 I/netd]
tetherGetStats() <1.03ms>

[06-12 13:14:13.764 2218:2218 D/ImageWallpaper]
wallpaper visibility changes to: false

[06-12 13:14:14.125 2218:2218 D/StatusBar]
disable<e i a s b h r c s > disable2<q i n >

@Jackeagle

**Comment by San0621** [comment]
Logcat link
https://drive.google.com/file/d/1gRfpmYZ_fJsYGSbPUfj4ZyQGNFrzvM_b/view?usp=drivesdk

**Comment by ericswpark** [comment]
Hello, this is a bug with a specific device. Please file this issue with the respective device repository. Thanks!
