### ISSUE TITLE
[BUG] Sytem Intelligence Keeps stopping (Poco X2 || Bliss v17.2)

### ISSUE THREAD

**Issue by jagadish8550** [BlissRoms/bug_reports#76]
### Issue type

Other

### Device

phoenix

### Bliss build

v17.2 - 2024-02-12 GApps build

### Bug Description

System Intelligence app keeps crashing randomly.

Thanks maintainers and devs for the amazing rom!

### Steps to reproduce

when turned phone is restarted.
will crash randomly.

### Expected Behavior

App should not crash

### Current Behavior

App is crashing

### Relevant log (logcat/build log)

```shell
time: 1709313306441
device fp:POCO/bliss_phoenix/phoenix:14/UQ1A.240205.004/nobody02122217:userdebug/test-keys
product board:sm6150
blissfest vers:17.2
msg: java.lang.SecurityException: Remote stack trace:
	at com.android.server.soundtrigger_middleware.SoundTriggerMiddlewarePermission.enforcePermissionForPreflight(SoundTriggerMiddlewarePermission.java:184)
	at com.android.server.soundtrigger_middleware.SoundTriggerMiddlewarePermission.listModules(SoundTriggerMiddlewarePermission.java:81)
	at com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareLogging.listModules(SoundTriggerMiddlewareLogging.java:132)
	at com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareService.listModulesAsMiddleman(SoundTriggerMiddlewareService.java:100)
	at com.android.server.soundtrigger.SoundTriggerService.listUnderlyingModuleProperties(SoundTriggerService.java:302)
stacktrace: java.lang.SecurityException: Failed to obtain permission android.permission.CAPTURE_AUDIO_HOTWORD for identity android.media.permission.Identity{uid: 10376, pid: 22929, packageName: com.google.android.as, attributionTag: null}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at com.android.internal.app.ISoundTriggerService$Stub$Proxy.listModuleProperties(ISoundTriggerService.java:316)
	at android.media.soundtrigger.SoundTriggerManager.<init>(SoundTriggerManager.java:105)
	at android.app.SystemServiceRegistry$90.createService(SystemServiceRegistry.java:1131)
	at android.app.SystemServiceRegistry$90.createService(SystemServiceRegistry.java:1127)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:2019)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1693)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:2212)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:934)
	at android.content.Context.getSystemService(Context.java:4420)
	at vcd.<init>(PG:8)
	at dke.cj(PG:11)
	at dkl.i(PG:1932)
	at dkl.a(PG:43)
	at wja.a(PG:16)
	at wiz.a(PG:5)
	at dke.az(PG:46)
	at dkl.e(PG:2037)
	at dkl.a(PG:13)
	at wja.a(PG:16)
	at dxa.run(PG:229)
	at gom.g(PG:2)
	at com.google.android.apps.miphone.aiai.app.AiAiContentCaptureService.onActivityEvent(PG:14)
	at android.service.contentcapture.ContentCaptureService.handleOnActivityEvent(ContentCaptureService.java:632)
	at android.service.contentcapture.ContentCaptureService.-$$Nest$mhandleOnActivityEvent(Unknown Source:0)
	at android.service.contentcapture.ContentCaptureService$1.$r8$lambda$ygtT3C0mTdyCy5SFIo3T8BDwrEE(Unknown Source:0)
	at android.service.contentcapture.ContentCaptureService$1$$ExternalSyntheticLambda1.accept(Unknown Source:4)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:87)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.soundtrigger_middleware.SoundTriggerMiddlewarePermission.enforcePermissionForPreflight(SoundTriggerMiddlewarePermission.java:184)
	at com.android.server.soundtrigger_middleware.SoundTriggerMiddlewarePermission.listModules(SoundTriggerMiddlewarePermission.java:81)
	at com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareLogging.listModules(SoundTriggerMiddlewareLogging.java:132)
	at com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareService.listModulesAsMiddleman(SoundTriggerMiddlewareService.java:100)
	at com.android.server.soundtrigger.SoundTriggerService.listUnderlyingModuleProperties(SoundTriggerService.java:302)
```

### Screenshots or videos

![SysInt](https://github.com/BlissRoms/bug_reports/assets/96580356/716d8476-ef63-45d1-9617-f5c8fac7c4fb)

### Acknowledgements

- [X] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by StudioKeys** [comment]
Since phoenix is not in active maintanence and this issue doesnt bother any version now i think, so closing it out
