### ISSUE TITLE
[BUG] video playback broken (Pixel 4a || Bliss v17.2 & Bliss v17.3)

### ISSUE THREAD

**Issue by Ciancy28** [BlissRoms/bug_reports#79]
### Issue type

Device-specific issue

### Device

Pixel 4a (sunfish)

### Bliss build

Bliss-v17.3-sunfish-OFFICIAL-gapps-20240317

### Bug Description

h264 decoding/playback fails most of the time, vp8/vp9/h265 playback seems fine
EDIT: I'm now getting decoding failures with vp9 and other codecs as well, it just happens less often
30 fps video playback also seems to bring the screen refreshrate down to 30 hz (making the entire device laggy) until a 60 fps video is played, this is due to some android feature designed for variable refresh rate displays that should be disabled on the 4a as it only features a constant refresh rate 60 hz screen
Issue was also present in the previous build

### Steps to reproduce

play an h264 encoded video in any app

### Expected Behavior

the video should play

### Current Behavior

video playback stops, newpipe and telegram x both display a media decoding failure error message
the logcat was taken while attempting to playback a 384x384 video message on telegram x

### Relevant log (logcat/build log)

```shell
03-18 18:47:34.461  1173 21172 E QC2Comp : [avcD_28] Queued: Skip logging corrupted work
03-18 18:47:34.461  1173 21172 E QC2Comp : [avcD_28] Returning work with no input buffer and not marked EOS
03-18 18:47:34.461  1173 21172 E QC2Comp : [avcD_28] Done: Skip logging corrupted work
03-18 18:47:34.462  8593 21171 D CCodecBufferChannel: [c2.qti.avc.decoder#443] flushed work; ignored.
03-18 18:47:34.462  8593 21171 D PipelineWatcher: onWorkDone: frameIndex not found (0); ignored
03-18 18:47:34.462  8593 21171 I CCodecBufferChannel: [c2.qti.avc.decoder#443] onWorkDone: incorrect number of worklets: 0
03-18 18:47:34.463  8593 21170 E MediaCodec: Codec reported err 0x80000000/UNKNOWN_ERROR, actionCode 0, while in state 6/STARTED
03-18 18:47:34.463  8593 21170 D MediaCodec: flushMediametrics
03-18 18:47:34.463  8593 21170 D SurfaceUtils: disconnecting from surface 0xb40000725f4b2490, reason disconnectFromSurface
03-18 18:47:34.464  8593  8892 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) dequeueBuffer: BufferQueue has no connected producer
03-18 18:47:34.464  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.464  1173 21175 D C2BqBuffer: cannot dequeue buffer -19
03-18 18:47:34.464  1173 21175 E QC2Buf  : allocate: failed to alloc graphic block w(384)/h(384)/f(7fa30c06)/usage(20010000)
03-18 18:47:34.464  1173 21175 W QC2V4l2Codec: [avcD_28] Graphic output-buf allocation failed!
03-18 18:47:34.464  1173 21175 E QC2V4l2Codec: [avcD_28] Error during buffer allocation
03-18 18:47:34.464  8593  8892 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) dequeueBuffer: BufferQueue has no connected producer
03-18 18:47:34.464  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.464  1173 21175 D C2BqBuffer: cannot dequeue buffer -19
03-18 18:47:34.464  1173 21175 E QC2Buf  : allocate: failed to alloc graphic block w(384)/h(384)/f(7fa30c06)/usage(20010000)
03-18 18:47:34.465  1173 21175 W QC2V4l2Codec: [avcD_28] Graphic output-buf allocation failed!
03-18 18:47:34.465  1173 21175 E QC2V4l2Codec: [avcD_28] Error during buffer allocation
03-18 18:47:34.465  8593  8892 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) dequeueBuffer: BufferQueue has no connected producer
03-18 18:47:34.465  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.465  1173 21175 D C2BqBuffer: cannot dequeue buffer -19
03-18 18:47:34.465  1173 21175 E QC2Buf  : allocate: failed to alloc graphic block w(384)/h(384)/f(7fa30c06)/usage(20010000)
03-18 18:47:34.465  1173 21175 W QC2V4l2Codec: [avcD_28] Graphic output-buf allocation failed!
03-18 18:47:34.465  1173 21175 E QC2V4l2Codec: [avcD_28] Error during buffer allocation
03-18 18:47:34.465  8593  8892 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) dequeueBuffer: BufferQueue has no connected producer
03-18 18:47:34.466  1173 21175 D C2BqBuffer: cannot dequeue buffer -19
03-18 18:47:34.466  1173 21175 E QC2Buf  : allocate: failed to alloc graphic block w(384)/h(384)/f(7fa30c06)/usage(20010000)
03-18 18:47:34.466  1173 21175 W QC2V4l2Codec: [avcD_28] Graphic output-buf allocation failed!
03-18 18:47:34.466  1173 21175 E QC2V4l2Codec: [avcD_28] Error during buffer allocation
03-18 18:47:34.466  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.466  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.467  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.467  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.468  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.468  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.468  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.469  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.469  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.470  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.470  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.470  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.470  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.471  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.471  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.471  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.471  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.472  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.472  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.472  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.472  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.473  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.473  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.473  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.473  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.473  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.474  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.474  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.474  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.474  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.474  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.475  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.475  8593 21170 E BufferQueueProducer: [SurfaceTexture-0-8593-31](id:219100000026,api:0,p:-1,c:8593) cancelBuffer: BufferQueue has no connected producer
03-18 18:47:34.475  1173  2580 E QC2Comp : queue_nb disallowed in ERROR state
03-18 18:47:34.481  8593 21167 E MediaCodecVideoRenderer: Video codec error
03-18 18:47:34.481  8593 21167 E MediaCodecVideoRenderer:   android.media.MediaCodec$CodecException: Error 0x80000000
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal: Playback error
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:   Q0.n: MediaCodecVideoRenderer error, index=2, format=Format(2, null, null, video/avc, avc1.64000A, -1, null, [384, 384, 22.650297, ColorInfo(BT601, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at Q0.S.handleMessage(SourceFile:447)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:205)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:294)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:   Caused by: b1.i: Decoder failed: c2.qti.avc.decoder
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at b1.m.G(SourceFile:5)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at V0.t.y(SourceFile:228)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at b1.m.y(SourceFile:1)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at Q0.S.e(SourceFile:1069)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       at Q0.S.handleMessage(SourceFile:281)
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:       ... 4 more
03-18 18:47:34.482  8593 21167 E ExoPlayerImplInternal:   Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
03-18 18:47:34.482  8593 21167 I Surface : Surface::setFrameRate is deprecated, setFrameRate hint is dropped as destination is not SurfaceFlinger
03-18 18:47:34.483  8593 21170 E MediaCodec: flush() is valid only at Executing states; currently at Released state
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal: Disable failed.
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:   java.lang.IllegalStateException: flush() is valid only at Executing states; currently at Released state
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:   
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2504)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at V0.c.flush(SourceFile:8)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at V0.t.L(SourceFile:6)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at V0.t.M(SourceFile:67)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at V0.t.o(SourceFile:14)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at b1.m.o(SourceFile:19)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at Q0.S.d(SourceFile:64)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at Q0.S.D(SourceFile:55)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at Q0.S.a0(SourceFile:13)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at Q0.S.handleMessage(SourceFile:563)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:205)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:294)
03-18 18:47:34.483  8593 21167 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
03-18 18:47:34.487  1173  2580 I QC2Comp : NOTE: Release returning: 0 (OK=0)
03-18 18:47:34.487  1173  2580 D C2BqBuffer: configuring null producer: igbp_information(0)
03-18 18:47:34.488  8593 21170 D MediaCodec: flushMediametrics
03-18 18:47:34.489  8593 21170 D MediaCodec: flushMediametrics
03-18 18:47:34.489  8593 21170 W MediaCodec: no metrics handle found
03-18 18:47:34.490  8593 21179 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
03-18 18:47:34.490  1173  2581 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
03-18 18:47:34.490  1173  2581 I QC2CompStore: Deleting component(c2.qti.avc.decoder) id(28)
03-18 18:47:34.497  1173  2581 I QC2V4l2Driver: [avcD_28] Closed device driver with fd: 12
03-18 18:47:34.497  1173  2581 I QC2Comp : [avcD_28] Deallocated component c2.qti.avc.decoder [id=28]
03-18 18:47:34.510  8593  8593 I ExoPlayerImpl: Release 81363da [AndroidXMedia3/1.3.0] [sunfish, Pixel 4a, Google, 34] [media3.common, media3.decoder.opus, media3.decoder.vpx, media3.decoder.flac, media3.decoder.ffmpeg, media3.exoplayer, media3.decoder, media3.datasource, media3.extractor]
03-18 18:47:34.542  2551  2694 W Parcel  : Expecting binder but got null!
```

### Screenshots or videos

![Immagine 2024-03-18 185533](https://github.com/BlissRoms/bug_reports/assets/77066322/98774f35-fdbe-4c69-8627-07b176cdc0d0)
![Immagine 2024-03-18 185549](https://github.com/BlissRoms/bug_reports/assets/77066322/b86431e4-1cc8-4734-b40e-26498462cb05)

### Possible Solution

Evolution X mantainer might have one, both issues were present and fixed in that rom

### Acknowledgements

- [X] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by Ciancy28** [comment]
@srgrusso

In case you weren't aware of this, I think that should get you notified

rest of the rom works perfectly and I'm very happy with it, thanks for your work.

**Comment by StudioKeys** [comment]
I hope it was resolved, but since sunfish is not in active maintainence, im marking this issue as closed
