### ISSUE TITLE
[BUG] <!-- System UI Crashing -->

### ISSUE THREAD

**Issue by Vaalu007** [BlissRoms/bug_reports#81]
### Issue type

User interface

### Device

phoenix

### Bliss build

Bliss-v17.3-phoenix-OFFICIAL-gapps-20240314

### Bug Description

swiping down the status bar when using some apps System UI crashed. It's a random issue until last week but right now it crashes frequently when also in home screen

### Steps to reproduce

Open any app 
use it some times and swipe down the status bar when inside that app

### Expected Behavior

Swiping down the status bar to open the QS

### Current Behavior

It causing the System UI crash

### Relevant log (logcat/build log)

```shell
time: 1712748802625
device fp:POCO/bliss_phoenix/phoenix:14/UQ1A.240205.004/nobody03141400:userdebug/test-keys
product board:sm6150
blissfest vers:17.3
msg: java.lang.NullPointerException: Remote stack trace:
	at java.util.HashSet.contains(HashSet.java:204)
	at com.android.internal.util.bliss.HideDeveloperStatusUtils.shouldHideDevStatus(HideDeveloperStatusUtils.java:22)
	at android.provider.Settings$Global.getInt(Settings.java:18507)
	at com.android.server.pm.UserManagerService.getUserSwitchability(UserManagerService.java:2246)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:1235)
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3063)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.os.IUserManager$Stub$Proxy.getUserSwitchability(IUserManager.java:2563)
	at android.os.UserManager.getUserSwitchability(UserManager.java:2487)
	at com.android.systemui.user.domain.interactor.UserInteractor$canSwitchUsers$2.invokeSuspend(go/retraceme 38786c71ca7b6a3e2e0aefe92be6ca57c771a13bcfbd4c64fb79b250540bbc80:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(go/retraceme 38786c71ca7b6a3e2e0aefe92be6ca57c771a13bcfbd4c64fb79b250540bbc80:8)
	at kotlinx.coroutines.DispatchedTask.run(go/retraceme 38786c71ca7b6a3e2e0aefe92be6ca57c771a13bcfbd4c64fb79b250540bbc80:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(go/retraceme 38786c71ca7b6a3e2e0aefe92be6ca57c771a13bcfbd4c64fb79b250540bbc80:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(go/retraceme 38786c71ca7b6a3e2e0aefe92be6ca57c771a13bcfbd4c64fb79b250540bbc80:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(go/retraceme 38786c71ca7b6a3e2e0aefe92be6ca57c771a13bcfbd4c64fb79b250540bbc80:93)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@749b76e, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at java.util.HashSet.contains(HashSet.java:204)
	at com.android.internal.util.bliss.HideDeveloperStatusUtils.shouldHideDevStatus(HideDeveloperStatusUtils.java:22)
	at android.provider.Settings$Global.getInt(Settings.java:18507)
	at com.android.server.pm.UserManagerService.getUserSwitchability(UserManagerService.java:2246)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:1235)
```

### Acknowledgements

- [ ] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by shripal17** [comment]
Is this still happening on v17.5?

**Comment by StudioKeys** [comment]
Since this issue is stale and no replies have been given unto the maintainer, closing
